### ISSUE TITLE
建议接收服务器数据的时候增加超时机制

### ISSUE THREAD

**Issue by KandyYe** [vnpy/vnpy_websocket#3]
在异步接收服务器数据的时候，如果服务器一直不给数据，将导致一直等待：

async for msg in self._ws:
          text: str = msg.data
          self._record_last_received_text(text)

          data: dict = self.unpack_data(text)
          self.on_packet(data)

建议增加超时机制，一段时间没有收到服务器数据，可以退出等待，断开重连。

**Comment by vnpy** [comment]
这里查了下aiohttp的源码，上述的_ws对象的__anext__方法，没有提供传入超时参数的功能，目前无法支持了。

如果有解决思路欢迎发PR。

**Comment by poloxue** [comment]
看了下 anext 的代码：
```python
msg = await self.receive()
if msg.type in (WSMsgType.CLOSE, WSMsgType.CLOSING, WSMsgType.CLOSED):
      raise StopAsyncIteration
 return msg
```

把这段拿出来替换用 asyncio wait_for 应该就行了。

```python
While True:
  try: 
    msg = await asyncio.wait_for(self.receive(), timeout=30)
    if msg.type in (WSMsgType.CLOSE, WSMsgType.CLOSING, WSMsgType.CLOSED):
          raise StopAsyncIteration
    # continue doing
  except asyncio.TiimeoutError:
      # reconnect
````
补充：
ws_connect 的源码本身是支持 receive_timeout 的。
